name: giuaky_maiphuong
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: 1.18.0
  flutter:
    sdk: flutter
  meta: 1.15.0
  material_color_utilities: 0.11.1
  plugin_platform_interface: ^2.1.8
  stack_trace: 1.11.1
  string_scanner: 1.2.0  # Align with flutter_test
  test_api: 0.7.2  # Align with flutter_test
  vm_service: 14.2.4  # Align with flutter_test
  web: ^1.1.0
  firebase_database: ^11.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.3
  firebase_app_check: ^0.3.1+3
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
